//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Andrewtate
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stantion
    {
        public int ID_Station { get; set; }
        public string Name { get; set; }
        public string Town { get; set; }
        public Nullable<int> Size { get; set; }
        public Nullable<int> Traint_ID { get; set; }
    
        public virtual Train Train { get; set; }
    }
}
